<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="lab2.1.css"?>

<!DOCTYPE root [
<!ELEMENT root (logo,nav-menu,table)>
<!ELEMENT logo (logo-text)>
<!ELEMENT logo-text (#PCDATA)>

<!ELEMENT nav-menu (menu+)>
<!ELEMENT menu (#PCDATA)>
<!ATTLIST menu is-unique (active|not-active) "not-active">


<!ELEMENT table (table-header, row*)>
<!ELEMENT table-header (#PCDATA)>
<!ELEMENT row (row-header, row-text)>
<!ATTLIST row id ID #REQUIRED>
<!ELEMENT row-header (#PCDATA)>
<!ELEMENT row-text ANY>

<!ELEMENT capitalize (#PCDATA)>
<!ELEMENT overline (#PCDATA)>
<!ELEMENT underline (#PCDATA)>
]>

<root>
    <logo>
        <logo-text>Lab 2.1 Онлайн конференції</logo-text>
    </logo>

    <nav-menu>
        <menu>Головна</menu>
        <menu>Підписки</menu>
        <menu is-unique="active">Про нас</menu>
    </nav-menu>

    <table>
        <table-header>Переваги сервісу онлайн-конференцій</table-header>
        <row id="r1">
            <row-header>Зручність</row-header>
            <row-text>
                <capitalize>Онлайн-конференції дозволяють швидко обмінюватись інформацією,
                    що часто призводить до поліпшення управління проектами.</capitalize> Тільки
                подумайте про це: ваші співробітники чітко знають, що і коли робити, помилок можна
                уникнути, а всі завдання вирішуються швидше. Зустрічі наживо уповільнюють процес
                ухвалення рішення, тому що процес збору окремих співробітників займає більше часу. </row-text>
        </row>

        <row id="r2">
            <row-header>Швидкість</row-header>
            <row-text>
                <overline>Спільна робота онлайн забезпечує більш високий рівень зручності, ніж
                зустрічі
                    наживо</overline>. Наприклад, коли ви зустрічаєтеся зі своїми співробітниками
                та/або колегами в режимі онлайн, вам не потрібно їхати в певне місце. Кожен учасник
                може бути присутнім на зустрічі, зручно розташувавшись біля свого комп'ютера —
                навіть якщо цей комп'ютер розташований за тисячі кілометрів від місцезнаходження
                іншого учасника. Це величезна перевага для команд віддалених співробітників. Це
                також зручно для організаторів, які планують великомасштабні заходи. <underline>
                Важко розмістити 25 осіб у
                    приміщенні в режимі
                    зустрічі наживо, але в цифровому середовищі простір не є проблемою</underline>. </row-text>
        </row>

        <row id="r3">
            <row-header>Можливість запису</row-header>
            <row-text>
                Якщо ключові члени команди не можуть відвідати заплановану зустріч?
                В умовах організації особистої зустрічі вам доведеться або
                переносити її або робити докладні нотатки для відсутніх учасників.
                Жодне з цих рішень не є ідеальним сценарієм.
                Онлайн-конференції можна легко записати. Потім відеозапис можна
                надіслати електронною поштою будь-якому учаснику, який був
                відсутній на онлайн-нараді.
            </row-text>
        </row>

    </table>
</root>